# Generated by Django 5.2.11 on 2026-02-11 21:55

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    for article in Article.objects.all():
        base_slug = slugify(article.title) or f"article-{article.pk}"
        slug = base_slug
        counter = 1
        while Article.objects.filter(slug=slug).exclude(pk=article.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        article.slug = slug
        article.save(update_fields=["slug"])

    Category = apps.get_model("blog", "Category")
    for category in Category.objects.all():
        base_slug = slugify(category.name) or f"category-{category.pk}"
        slug = base_slug
        counter = 1
        while Category.objects.filter(slug=slug).exclude(pk=category.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        category.slug = slug
        category.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        # Step 1: Add slug fields without unique constraint
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, default=""),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, default=""),
        ),
        # Step 2: Populate slugs from existing data
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        # Other field changes
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
