# Generated by Django 5.2.11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_image_article_likes"),
        ("blog", "0002_article_slug_category_slug_alter_article_id_and_more"),
    ]

    operations = [
    ]
